/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	endpointgroupbindingv1alpha1 "github.com/h3poteto/aws-global-accelerator-controller/pkg/apis/endpointgroupbinding/v1alpha1"
	scheme "github.com/h3poteto/aws-global-accelerator-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EndpointGroupBindingsGetter has a method to return a EndpointGroupBindingInterface.
// A group's client should implement this interface.
type EndpointGroupBindingsGetter interface {
	EndpointGroupBindings(namespace string) EndpointGroupBindingInterface
}

// EndpointGroupBindingInterface has methods to work with EndpointGroupBinding resources.
type EndpointGroupBindingInterface interface {
	Create(ctx context.Context, endpointGroupBinding *endpointgroupbindingv1alpha1.EndpointGroupBinding, opts v1.CreateOptions) (*endpointgroupbindingv1alpha1.EndpointGroupBinding, error)
	Update(ctx context.Context, endpointGroupBinding *endpointgroupbindingv1alpha1.EndpointGroupBinding, opts v1.UpdateOptions) (*endpointgroupbindingv1alpha1.EndpointGroupBinding, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, endpointGroupBinding *endpointgroupbindingv1alpha1.EndpointGroupBinding, opts v1.UpdateOptions) (*endpointgroupbindingv1alpha1.EndpointGroupBinding, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*endpointgroupbindingv1alpha1.EndpointGroupBinding, error)
	List(ctx context.Context, opts v1.ListOptions) (*endpointgroupbindingv1alpha1.EndpointGroupBindingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *endpointgroupbindingv1alpha1.EndpointGroupBinding, err error)
	EndpointGroupBindingExpansion
}

// endpointGroupBindings implements EndpointGroupBindingInterface
type endpointGroupBindings struct {
	*gentype.ClientWithList[*endpointgroupbindingv1alpha1.EndpointGroupBinding, *endpointgroupbindingv1alpha1.EndpointGroupBindingList]
}

// newEndpointGroupBindings returns a EndpointGroupBindings
func newEndpointGroupBindings(c *OperatorV1alpha1Client, namespace string) *endpointGroupBindings {
	return &endpointGroupBindings{
		gentype.NewClientWithList[*endpointgroupbindingv1alpha1.EndpointGroupBinding, *endpointgroupbindingv1alpha1.EndpointGroupBindingList](
			"endpointgroupbindings",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *endpointgroupbindingv1alpha1.EndpointGroupBinding {
				return &endpointgroupbindingv1alpha1.EndpointGroupBinding{}
			},
			func() *endpointgroupbindingv1alpha1.EndpointGroupBindingList {
				return &endpointgroupbindingv1alpha1.EndpointGroupBindingList{}
			},
		),
	}
}
