/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/h3poteto/aws-global-accelerator-controller/pkg/apis/endpointgroupbinding/v1alpha1"
	scheme "github.com/h3poteto/aws-global-accelerator-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EndpointGroupBindingsGetter has a method to return a EndpointGroupBindingInterface.
// A group's client should implement this interface.
type EndpointGroupBindingsGetter interface {
	EndpointGroupBindings(namespace string) EndpointGroupBindingInterface
}

// EndpointGroupBindingInterface has methods to work with EndpointGroupBinding resources.
type EndpointGroupBindingInterface interface {
	Create(ctx context.Context, endpointGroupBinding *v1alpha1.EndpointGroupBinding, opts v1.CreateOptions) (*v1alpha1.EndpointGroupBinding, error)
	Update(ctx context.Context, endpointGroupBinding *v1alpha1.EndpointGroupBinding, opts v1.UpdateOptions) (*v1alpha1.EndpointGroupBinding, error)
	UpdateStatus(ctx context.Context, endpointGroupBinding *v1alpha1.EndpointGroupBinding, opts v1.UpdateOptions) (*v1alpha1.EndpointGroupBinding, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.EndpointGroupBinding, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.EndpointGroupBindingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.EndpointGroupBinding, err error)
	EndpointGroupBindingExpansion
}

// endpointGroupBindings implements EndpointGroupBindingInterface
type endpointGroupBindings struct {
	client rest.Interface
	ns     string
}

// newEndpointGroupBindings returns a EndpointGroupBindings
func newEndpointGroupBindings(c *OperatorV1alpha1Client, namespace string) *endpointGroupBindings {
	return &endpointGroupBindings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the endpointGroupBinding, and returns the corresponding endpointGroupBinding object, and an error if there is any.
func (c *endpointGroupBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.EndpointGroupBinding, err error) {
	result = &v1alpha1.EndpointGroupBinding{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("endpointgroupbindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EndpointGroupBindings that match those selectors.
func (c *endpointGroupBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.EndpointGroupBindingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.EndpointGroupBindingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("endpointgroupbindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested endpointGroupBindings.
func (c *endpointGroupBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("endpointgroupbindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a endpointGroupBinding and creates it.  Returns the server's representation of the endpointGroupBinding, and an error, if there is any.
func (c *endpointGroupBindings) Create(ctx context.Context, endpointGroupBinding *v1alpha1.EndpointGroupBinding, opts v1.CreateOptions) (result *v1alpha1.EndpointGroupBinding, err error) {
	result = &v1alpha1.EndpointGroupBinding{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("endpointgroupbindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(endpointGroupBinding).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a endpointGroupBinding and updates it. Returns the server's representation of the endpointGroupBinding, and an error, if there is any.
func (c *endpointGroupBindings) Update(ctx context.Context, endpointGroupBinding *v1alpha1.EndpointGroupBinding, opts v1.UpdateOptions) (result *v1alpha1.EndpointGroupBinding, err error) {
	result = &v1alpha1.EndpointGroupBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("endpointgroupbindings").
		Name(endpointGroupBinding.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(endpointGroupBinding).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *endpointGroupBindings) UpdateStatus(ctx context.Context, endpointGroupBinding *v1alpha1.EndpointGroupBinding, opts v1.UpdateOptions) (result *v1alpha1.EndpointGroupBinding, err error) {
	result = &v1alpha1.EndpointGroupBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("endpointgroupbindings").
		Name(endpointGroupBinding.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(endpointGroupBinding).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the endpointGroupBinding and deletes it. Returns an error if one occurs.
func (c *endpointGroupBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("endpointgroupbindings").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *endpointGroupBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("endpointgroupbindings").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched endpointGroupBinding.
func (c *endpointGroupBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.EndpointGroupBinding, err error) {
	result = &v1alpha1.EndpointGroupBinding{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("endpointgroupbindings").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
