name: E2E

on:
  push:
    branches:
      - master
  pull_request:

env:
  KOPS_VERSION: 1.23.0
  KUBECTL_VERSION: 1.23.4
  KOPS_STATE_STORE: s3://e2e-global-accelerator
  KOPS_CLUSTER_NAME: e2e-global-accelerator.k8s.h3poteto.dev

permissions:
  id-token: write
  contents: read

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0'
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::564677439943:role/kops-from-github-role
          aws-region: ap-northeast-1
      - run: |
          aws ec2 describe-instances
      - name: Install kubectl
        env:
          KUBECTL_VERSION: ${{ env.KUBECTL_VERSION }}
          BIN_DIR: ${{ github.workspace }}/tools/
        run: |
          mkdir -p $BIN_DIR
          curl -sSLo "$BIN_DIR/kubectl" "https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
          chmod +x "$BIN_DIR/kubectl"
          echo "$BIN_DIR" >> "$GITHUB_PATH"
      - name: Install kOps
        env:
          KOPS_VERSION: ${{ env.KOPS_VERSION }}
          BIN_DIR: ${{ github.workspace }}/tools/
        run: |
          mkdir -p $BIN_DIR
          curl -sSLo "$BIN_DIR/kops" "https://github.com/kubernetes/kops/releases/download/v${KOPS_VERSION}/kops-linux-amd64"
          chmod +x "$BIN_DIR/kops"
          echo "$BIN_DIR" >> "$GITHUB_PATH"
      - name: Check commit message
        if: contains(join(github.event.head_commit.message, ';'), '[e2e]') != true
        run: |
          exit 0
      - name: Create cluster
        run: |
          mkdir ~/.ssh
          kops create -f e2e/cluster.yaml
          kops create secret --name e2e-global-accelerator.k8s.h3poteto.dev sshpublickey admin -i ~/.ssh/id_rsa.pub
          kops update cluster e2e-global-accelerator.k8s.h3poteto.dev --yes --admin
          kops validate cluster --wait 15m
      - name: Cleanup cluster
        if: always()
        run: |
          kops delete cluster


